# Generated by Django 3.0.8 on 2020-07-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philjobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
