# Generated by Django 3.0.8 on 2020-07-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philjobs', '0002_auto_20200703_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
    ]
